1. df_krx의 Marcap(시가총액)를 활용하여 시가총액 순위를 새로운 칼럼으로 정의 (칼럼명 : Marcap_rank)
  - Marcap(시가총액)이 높을수록 낮은순위(1등에 가깝다.)
2. 순위데이터(Marcap_rank)를 활용하여 100위 이하는 large-cap, 100~300위는 mid-cap, 이외 순위는 small-cap으로 새로운 칼럼 선언(칼럼명 : Marcap_size)
3. Marcap_size(large-cap, mid-cap,small-cap) 수익률(ChagesRatio)의 평균을 출력

In [19]:
import pandas as pd
df_krx = pd.read_csv("https://raw.githubusercontent.com/jin0choi1216/dataset/main/KRX_stocks.csv", index_col=0)
df_krx

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,NaN,67100,2,-1100,-1.61,67100,67400,66900,7032462,471934306900,400572409105000,5969782550,STK
1,373220,KR7373220003,LG에너지솔루션,KOSPI,NaN,546000,1,11000,2.06,527000,549000,525000,249493,135513119000,127764000000000,234000000,STK
2,000660,KR7000660001,SK하이닉스,KOSPI,NaN,116500,2,-4400,-3.64,117400,118300,115300,3533647,412064064200,84812275522500,728002365,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,NaN,757000,2,-6000,-0.79,755000,764000,754000,23435,17763884000,53878718000000,71174000,STK
4,005490,KR7005490008,POSCO홀딩스,KOSPI,NaN,577000,2,-2000,-0.35,567000,583000,561000,904736,519579225000,48797599710000,84571230,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2743,001527,KR7001522002,동양2우B,KOSPI,NaN,10150,2,-10,-0.10,10040,10220,10040,53,534860,3131975350,308569,STK
2744,288490,KR7288490006,나라소프트,KONEX,일반기업부,56,2,-1,-1.75,58,58,55,50157,2797792,2422952280,43267005,KNX
2745,245450,KR7245450002,씨앤에스링크,KONEX,일반기업부,1500,1,100,7.14,1500,1500,1500,1,1500,2369940000,1579960,KNX
2746,322190,KR7322190000,베른,KONEX,일반기업부,139,2,-4,-2.80,150,150,122,10414,1281538,1240602383,8925197,KNX
2747,308700,KR7308700004,테크엔,KONEX,일반기업부,203,2,-28,-12.12,265,265,201,3076,811976,812000000,4000000,KNX

In [22]:
df_krx['Marcap_rank'] = df_krx['Marcap'].rank(ascending=False)

df_krx['Marcap_size'] = df_krx['Marcap_rank'].apply(lambda x : 'large-cap' if x <= 100 else('mid-cap' if (x>100)&(x<=300) else 'small-cap'))

0          1.0
1          2.0
2          3.0
3          4.0
4          5.0
         ...
2743    2744.0
2744    2745.0
2745    2746.0
2746    2747.0
2747    2748.0
Name: Marcap, Length: 2748, dtype: float64

In [23]:
df_krx[['Marcap_size','ChagesRatio']].groupby('Marcap_size').mean()

             ChagesRatio
Marcap_size
large-cap      -0.151600
mid-cap        -0.645900
small-cap      -0.183321